---
github:
  owner: tonyo
  repo: alpaga
artifactProvider:
  name: none
targets:
  - name: github
    id: root
    tagOnly: true
    tagPrefix: 'test/'
  - name: github
    id: bla
    tagOnly: true
    tagPrefix: 'test/bla/'
